/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/vms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Vms
         * @description List all VMs with pagination.
         *
         *     Args:
         *         limit: Maximum number of results
         *         offset: Number of results to skip
         *         service: VM service
         *
         *     Returns:
         *         List of VMs with pagination metadata
         */
        get: operations["list_vms_vms_get"];
        put?: never;
        /**
         * Create Vm
         * @description Create a new VM.
         *
         *     Args:
         *         request: VM creation parameters
         *         service: VM service
         *
         *     Returns:
         *         Created VM response
         *
         *     Raises:
         *         ValidationError: If input is invalid
         *         CloudConnectionError: If cannot connect to cloud
         *         CloudOperationError: If cloud operation fails
         */
        post: operations["create_vm_vms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{vm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vm
         * @description Get VM by ID.
         *
         *     Args:
         *         vm_id: VM unique identifier
         *         service: VM service
         *
         *     Returns:
         *         VM response
         *
         *     Raises:
         *         NotFoundError: If VM not found
         */
        get: operations["get_vm_vms__vm_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Vm
         * @description Delete a VM.
         *
         *     Args:
         *         vm_id: VM unique identifier
         *         service: VM service
         *
         *     Raises:
         *         NotFoundError: If VM not found
         */
        delete: operations["delete_vm_vms__vm_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{vm_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Perform Vm Action
         * @description Perform action on VM (start, stop, reboot).
         *
         *     Args:
         *         vm_id: VM unique identifier
         *         request: Action parameters
         *         service: VM service
         *
         *     Returns:
         *         Action response
         *
         *     Raises:
         *         ValidationError: If action is invalid
         *         NotFoundError: If VM not found
         *         OperationNotAllowedError: If action not allowed in current state
         */
        post: operations["perform_vm_action_vms__vm_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Volumes
         * @description List all volumes with pagination.
         *
         *     Args:
         *         limit: Maximum number of results
         *         offset: Number of results to skip
         *         service: Volume service
         *
         *     Returns:
         *         List of volumes with pagination metadata
         */
        get: operations["list_volumes_volumes_get"];
        put?: never;
        /**
         * Create Volume
         * @description Create a new volume.
         *
         *     Args:
         *         request: Volume creation parameters
         *         service: Volume service
         *
         *     Returns:
         *         Created volume response
         */
        post: operations["create_volume_volumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volumes/{volume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Volume
         * @description Get volume by ID.
         *
         *     Args:
         *         volume_id: Volume unique identifier
         *         service: Volume service
         *
         *     Returns:
         *         Volume response
         */
        get: operations["get_volume_volumes__volume_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Volume
         * @description Delete a volume.
         *
         *     Args:
         *         volume_id: Volume unique identifier
         *         service: Volume service
         */
        delete: operations["delete_volume_volumes__volume_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volumes/{volume_id}/attach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach Volume
         * @description Attach volume to VM.
         *
         *     Args:
         *         volume_id: Volume unique identifier
         *         request: Attachment parameters
         *         service: Volume service
         *
         *     Returns:
         *         Updated volume response
         */
        post: operations["attach_volume_volumes__volume_id__attach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volumes/{volume_id}/detach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detach Volume
         * @description Detach volume from VM.
         *
         *     Args:
         *         volume_id: Volume unique identifier
         *         service: Volume service
         *
         *     Returns:
         *         Updated volume response
         */
        post: operations["detach_volume_volumes__volume_id__detach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Snapshots
         * @description List all snapshots with pagination.
         *
         *     Args:
         *         limit: Maximum number of results
         *         offset: Number of results to skip
         *         service: Volume service
         *
         *     Returns:
         *         List of snapshots with pagination metadata
         */
        get: operations["list_snapshots_snapshots_get"];
        put?: never;
        /**
         * Create Snapshot
         * @description Create a volume snapshot.
         *
         *     Args:
         *         request: Snapshot creation parameters
         *         service: Volume service
         *
         *     Returns:
         *         Created snapshot response
         */
        post: operations["create_snapshot_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Snapshot
         * @description Get snapshot by ID.
         *
         *     Args:
         *         snapshot_id: Snapshot unique identifier
         *         service: Volume service
         *
         *     Returns:
         *         Snapshot response
         */
        get: operations["get_snapshot_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Snapshot
         * @description Delete a snapshot.
         *
         *     Args:
         *         snapshot_id: Snapshot unique identifier
         *         service: Volume service
         */
        delete: operations["delete_snapshot_snapshots__snapshot_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Images
         * @description List available images with pagination.
         *
         *     Args:
         *         request: FastAPI request
         *         cloud: Cloud name (query parameter)
         *         limit: Maximum number of results (default: 100, max: 1000)
         *         offset: Number of results to skip (default: 0)
         *
         *     Returns:
         *         List of images with pagination info
         *
         *     Example:
         *         GET /images?cloud=ovh&limit=50&offset=0
         */
        get: operations["list_images_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flavors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Flavors
         * @description List available flavors with pagination.
         *
         *     Args:
         *         request: FastAPI request
         *         cloud: Cloud name (query parameter)
         *         limit: Maximum number of results (default: 100, max: 1000)
         *         offset: Number of results to skip (default: 0)
         *
         *     Returns:
         *         List of flavors with pagination info
         *
         *     Example:
         *         GET /flavors?cloud=ovh&limit=50&offset=0
         */
        get: operations["list_flavors_flavors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clouds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Clouds Status
         * @description Get status of all configured clouds.
         *
         *     Returns:
         *         dict: Available clouds and current active cloud
         */
        get: operations["get_clouds_status_clouds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint to verify API is running.
         *
         *     Returns:
         *         dict: Health status
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hello World
         * @description Hello World endpoint to verify basic functionality.
         *
         *     Returns:
         *         dict: Welcome message
         */
        get: operations["hello_world__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/cloud/{cloud_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cloud Health Check
         * @description Check if a specific cloud can be connected to.
         *
         *     This endpoint tests the actual connection to a cloud provider
         *     to ensure credentials are valid and the service is reachable.
         *
         *     Args:
         *         cloud_name: Name of the cloud to check (e.g., 'ovh', 'mock')
         *
         *     Returns:
         *         dict: Cloud health status with connection details
         */
        get: operations["cloud_health_check_health_cloud__cloud_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttachVolumeRequest
         * @description Request to attach a volume to a VM.
         * @example {
         *       "device": "/dev/vdb",
         *       "vm_id": "vm-12345"
         *     }
         */
        AttachVolumeRequest: {
            /**
             * Vm Id
             * @description VM to attach to
             */
            vm_id: string;
            /**
             * Device
             * @description Device path (e.g., /dev/vdb)
             */
            device?: string | null;
        };
        /**
         * CreateSnapshotRequest
         * @description Request to create a snapshot.
         * @example {
         *       "description": "Daily backup",
         *       "metadata": {
         *         "backup_type": "daily"
         *       },
         *       "name": "my-volume-snapshot",
         *       "volume_id": "vol-12345"
         *     }
         */
        CreateSnapshotRequest: {
            /**
             * Name
             * @description Snapshot name
             */
            name: string;
            /**
             * Volume Id
             * @description Volume to snapshot
             */
            volume_id: string;
            /**
             * Description
             * @description Snapshot description
             */
            description?: string | null;
            /**
             * Metadata
             * @description Custom metadata
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * CreateVMRequest
         * @description Request to create a new VM.
         * @example {
         *       "flavor_id": "2",
         *       "image_id": "8a2d8e80-c940-43fa-afa0-d2f8024fcf0a",
         *       "key_name": "my-key",
         *       "metadata": {
         *         "env": "production"
         *       },
         *       "name": "my-vm",
         *       "network_ids": [
         *         "net-123"
         *       ],
         *       "security_groups": [
         *         "default"
         *       ]
         *     }
         */
        CreateVMRequest: {
            /**
             * Name
             * @description VM name
             */
            name: string;
            /**
             * Image Id
             * @description Image ID to boot from
             */
            image_id: string;
            /**
             * Flavor Id
             * @description Flavor/instance type ID
             */
            flavor_id: string;
            /**
             * Network Ids
             * @description List of network IDs to attach
             */
            network_ids: string[];
            /**
             * Key Name
             * @description SSH key name for authentication
             */
            key_name?: string | null;
            /**
             * Security Groups
             * @description Security group names
             */
            security_groups?: string[];
            /**
             * Metadata
             * @description Custom metadata
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * CreateVolumeRequest
         * @description Request to create a new volume.
         * @example {
         *       "description": "Data volume",
         *       "metadata": {
         *         "env": "production"
         *       },
         *       "name": "my-volume",
         *       "size_gb": 100,
         *       "volume_type": "standard"
         *     }
         */
        CreateVolumeRequest: {
            /**
             * Name
             * @description Volume name
             */
            name: string;
            /**
             * Size Gb
             * @description Volume size in GB
             */
            size_gb: number;
            /**
             * Volume Type
             * @description Volume type (standard, ssd, etc.)
             */
            volume_type?: string | null;
            /**
             * Description
             * @description Volume description
             */
            description?: string | null;
            /**
             * Metadata
             * @description Custom metadata
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * FlavorResponse
         * @description Flavor response model.
         * @example {
         *       "created_at": "2025-05-15T10:30:00Z",
         *       "description": "Small flavor with 1 vCPU and 2GB RAM",
         *       "disk_gb": 20,
         *       "ephemeral_gb": 0,
         *       "id": "2",
         *       "is_public": true,
         *       "metadata": {
         *         "_raw": {
         *           "disk": 20,
         *           "id": "2",
         *           "name": "m1.small",
         *           "ram": 2048,
         *           "vcpus": 1
         *         }
         *       },
         *       "name": "m1.small",
         *       "ram_mb": 2048,
         *       "rxtx_factor": 1,
         *       "status": "AVAILABLE",
         *       "swap_mb": 0,
         *       "updated_at": "2025-05-15T10:30:00Z",
         *       "vcpus": 1
         *     }
         */
        FlavorResponse: {
            /**
             * Id
             * @description Unique flavor identifier
             */
            id: string;
            /**
             * Name
             * @description Flavor name (e.g., 'm1.small', 't2.micro')
             */
            name: string;
            /**
             * Status
             * @description Flavor status (AVAILABLE, UNKNOWN)
             */
            status: string;
            /**
             * Vcpus
             * @description Number of virtual CPUs
             */
            vcpus?: number | null;
            /**
             * Ram Mb
             * @description RAM in megabytes
             */
            ram_mb?: number | null;
            /**
             * Disk Gb
             * @description Root disk size in gigabytes
             */
            disk_gb?: number | null;
            /**
             * Ephemeral Gb
             * @description Ephemeral disk size in gigabytes
             */
            ephemeral_gb?: number | null;
            /**
             * Swap Mb
             * @description Swap disk size in megabytes
             */
            swap_mb?: number | null;
            /**
             * Rxtx Factor
             * @description Network receive/transmit bandwidth factor
             */
            rxtx_factor?: number | null;
            /**
             * Is Public
             * @description Whether flavor is available to all projects
             * @default true
             */
            is_public: boolean;
            /**
             * Description
             * @description Flavor description
             */
            description?: string | null;
            /**
             * Metadata
             * @description Flavor metadata including _raw OpenStack object
             */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * @description Flavor creation timestamp
             */
            created_at?: string | null;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageResponse
         * @description Image response model.
         * @example {
         *       "container_format": "bare",
         *       "created_at": "2025-05-15T10:30:00Z",
         *       "description": "Ubuntu 20.04 LTS base image",
         *       "disk_format": "qcow2",
         *       "id": "img-ubuntu-20-04",
         *       "is_protected": false,
         *       "is_public": true,
         *       "metadata": {
         *         "_raw": {
         *           "id": "img-ubuntu-20-04",
         *           "name": "Ubuntu 20.04 LTS",
         *           "properties": {},
         *           "status": "ACTIVE"
         *         }
         *       },
         *       "min_disk_gb": 5,
         *       "min_ram_mb": 512,
         *       "name": "Ubuntu 20.04 LTS",
         *       "size_bytes": 2147483648,
         *       "status": "ACTIVE",
         *       "updated_at": "2025-05-15T10:30:00Z"
         *     }
         */
        ImageResponse: {
            /**
             * Id
             * @description Unique image identifier
             */
            id: string;
            /**
             * Name
             * @description Image name
             */
            name: string;
            /**
             * Status
             * @description Image status (ACTIVE, QUEUED, SAVING, etc.)
             */
            status: string;
            /**
             * Size Bytes
             * @description Image size in bytes
             */
            size_bytes?: number | null;
            /**
             * Disk Format
             * @description Disk format (qcow2, raw, vmdk, etc.)
             */
            disk_format?: string | null;
            /**
             * Container Format
             * @description Container format (bare, ovf, etc.)
             */
            container_format?: string | null;
            /**
             * Is Public
             * @description Whether image is public
             * @default false
             */
            is_public: boolean;
            /**
             * Is Protected
             * @description Whether image is protected from deletion
             * @default false
             */
            is_protected: boolean;
            /**
             * Min Disk Gb
             * @description Minimum disk size required in GB
             */
            min_disk_gb?: number | null;
            /**
             * Min Ram Mb
             * @description Minimum RAM required in MB
             */
            min_ram_mb?: number | null;
            /**
             * Description
             * @description Image description
             */
            description?: string | null;
            /**
             * Metadata
             * @description Image metadata including _raw OpenStack object
             */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * @description Image creation timestamp
             */
            created_at?: string | null;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
        /** ListResponse[FlavorResponse] */
        ListResponse_FlavorResponse_: {
            /**
             * Success
             * @description Operation succeeded
             * @default true
             */
            success: boolean;
            /**
             * Data
             * @description List of items
             */
            data: components["schemas"]["FlavorResponse"][];
            /** @description Pagination metadata */
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** ListResponse[ImageResponse] */
        ListResponse_ImageResponse_: {
            /**
             * Success
             * @description Operation succeeded
             * @default true
             */
            success: boolean;
            /**
             * Data
             * @description List of items
             */
            data: components["schemas"]["ImageResponse"][];
            /** @description Pagination metadata */
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * PaginationMeta
         * @description Pagination metadata.
         */
        PaginationMeta: {
            /**
             * Total
             * @description Total number of items
             */
            total: number;
            /**
             * Page
             * @description Current page number
             */
            page: number;
            /**
             * Per Page
             * @description Items per page
             */
            per_page: number;
            /**
             * Pages
             * @description Total number of pages
             */
            pages: number;
        };
        /**
         * SnapshotResponse
         * @description Snapshot response schema.
         * @example {
         *       "created_at": "2024-01-15T10:30:00Z",
         *       "description": "Daily backup",
         *       "id": "snap-12345",
         *       "metadata": {
         *         "backup_type": "daily"
         *       },
         *       "name": "my-volume-snapshot",
         *       "size_gb": 100,
         *       "status": "AVAILABLE",
         *       "updated_at": "2024-01-15T10:30:00Z",
         *       "volume_id": "vol-12345"
         *     }
         */
        SnapshotResponse: {
            /**
             * Id
             * @description Snapshot unique identifier
             */
            id: string;
            /**
             * Name
             * @description Snapshot name
             */
            name: string;
            /**
             * Volume Id
             * @description Source volume ID
             */
            volume_id: string;
            /**
             * Size Gb
             * @description Snapshot size in GB
             */
            size_gb: number;
            /**
             * Status
             * @description Snapshot status
             */
            status: string;
            /**
             * Description
             * @description Description
             */
            description?: string | null;
            /**
             * Metadata
             * @description Custom metadata
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * @description Creation timestamp
             */
            created_at?: string | null;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
        /** SuccessResponse[SnapshotResponse] */
        SuccessResponse_SnapshotResponse_: {
            /**
             * Success
             * @description Operation succeeded
             * @default true
             */
            success: boolean;
            /** @description Response data */
            data: components["schemas"]["SnapshotResponse"];
            /**
             * Message
             * @description Optional success message
             */
            message?: string | null;
        };
        /** SuccessResponse[VMActionResponse] */
        SuccessResponse_VMActionResponse_: {
            /**
             * Success
             * @description Operation succeeded
             * @default true
             */
            success: boolean;
            /** @description Response data */
            data: components["schemas"]["VMActionResponse"];
            /**
             * Message
             * @description Optional success message
             */
            message?: string | null;
        };
        /** SuccessResponse[VMResponse] */
        SuccessResponse_VMResponse_: {
            /**
             * Success
             * @description Operation succeeded
             * @default true
             */
            success: boolean;
            /** @description Response data */
            data: components["schemas"]["VMResponse"];
            /**
             * Message
             * @description Optional success message
             */
            message?: string | null;
        };
        /** SuccessResponse[VolumeResponse] */
        SuccessResponse_VolumeResponse_: {
            /**
             * Success
             * @description Operation succeeded
             * @default true
             */
            success: boolean;
            /** @description Response data */
            data: components["schemas"]["VolumeResponse"];
            /**
             * Message
             * @description Optional success message
             */
            message?: string | null;
        };
        /**
         * VMActionRequest
         * @description Request for VM actions (start, stop, reboot).
         * @example {
         *       "action": "reboot"
         *     }
         */
        VMActionRequest: {
            /**
             * Action
             * @description Action to perform: start, stop, reboot
             */
            action: string;
        };
        /**
         * VMActionResponse
         * @description Response from VM action.
         * @example {
         *       "action": "reboot",
         *       "id": "vm-12345",
         *       "message": "VM reboot initiated"
         *     }
         */
        VMActionResponse: {
            /**
             * Id
             * @description VM unique identifier
             */
            id: string;
            /**
             * Action
             * @description Action performed
             */
            action: string;
            /**
             * Message
             * @description Action result message
             */
            message: string;
        };
        /**
         * VMResponse
         * @description VM response schema.
         * @example {
         *       "attached_volumes": [
         *         "vol-456"
         *       ],
         *       "created_at": "2024-01-15T10:30:00Z",
         *       "flavor_id": "2",
         *       "id": "vm-12345",
         *       "image_id": "8a2d8e80-c940-43fa-afa0-d2f8024fcf0a",
         *       "key_name": "my-key",
         *       "metadata": {
         *         "env": "production"
         *       },
         *       "name": "my-vm",
         *       "network_ids": [
         *         "net-123"
         *       ],
         *       "security_groups": [
         *         "default"
         *       ],
         *       "status": "ACTIVE",
         *       "updated_at": "2024-01-15T10:30:00Z"
         *     }
         */
        VMResponse: {
            /**
             * Id
             * @description VM unique identifier
             */
            id: string;
            /**
             * Name
             * @description VM name
             */
            name: string;
            /**
             * Status
             * @description VM status (BUILDING, ACTIVE, STOPPED, etc.)
             */
            status: string;
            /**
             * Image Id
             * @description Image ID
             */
            image_id: string;
            /**
             * Flavor Id
             * @description Flavor ID
             */
            flavor_id: string;
            /**
             * Network Ids
             * @description Attached network IDs
             */
            network_ids: string[];
            /**
             * Attached Volumes
             * @description Attached volume IDs
             */
            attached_volumes: string[];
            /**
             * Key Name
             * @description SSH key name
             */
            key_name?: string | null;
            /**
             * Security Groups
             * @description Security groups
             */
            security_groups: string[];
            /**
             * Metadata
             * @description Custom metadata
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * @description Creation timestamp
             */
            created_at?: string | null;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VolumeAttachmentResponse
         * @description Volume attachment information.
         */
        VolumeAttachmentResponse: {
            /**
             * Attachment Id
             * @description Attachment unique identifier
             */
            attachment_id: string;
            /**
             * Vm Id
             * @description VM identifier
             */
            vm_id: string;
            /**
             * Device
             * @description Device path
             */
            device: string;
        };
        /**
         * VolumeResponse
         * @description Volume response schema.
         * @example {
         *       "attachments": [
         *         {
         *           "attachment_id": "attach-123",
         *           "device": "/dev/vdb",
         *           "vm_id": "vm-12345"
         *         }
         *       ],
         *       "created_at": "2024-01-15T10:30:00Z",
         *       "description": "Data volume",
         *       "id": "vol-12345",
         *       "metadata": {
         *         "env": "production"
         *       },
         *       "name": "my-volume",
         *       "size_gb": 100,
         *       "status": "IN_USE",
         *       "updated_at": "2024-01-15T10:30:00Z",
         *       "volume_type": "standard"
         *     }
         */
        VolumeResponse: {
            /**
             * Id
             * @description Volume unique identifier
             */
            id: string;
            /**
             * Name
             * @description Volume name
             */
            name: string;
            /**
             * Size Gb
             * @description Volume size in GB
             */
            size_gb: number;
            /**
             * Status
             * @description Volume status (AVAILABLE, IN_USE, etc.)
             */
            status: string;
            /**
             * Volume Type
             * @description Volume type
             */
            volume_type?: string | null;
            /**
             * Description
             * @description Volume description
             */
            description?: string | null;
            /**
             * Attachments
             * @description Attachments
             */
            attachments: components["schemas"]["VolumeAttachmentResponse"][];
            /**
             * Metadata
             * @description Custom metadata
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * @description Creation timestamp
             */
            created_at?: string | null;
            /**
             * Updated At
             * @description Last update timestamp
             */
            updated_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_vms_vms_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                cloud?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vm_vms_post: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVMRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_VMResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vm_vms__vm_id__get: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path: {
                vm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_VMResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vm_vms__vm_id__delete: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path: {
                vm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    perform_vm_action_vms__vm_id__action_post: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path: {
                vm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VMActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_VMActionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_volumes_volumes_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                cloud?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_volume_volumes_post: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVolumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_VolumeResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_volume_volumes__volume_id__get: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path: {
                volume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_VolumeResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_volume_volumes__volume_id__delete: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path: {
                volume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_volume_volumes__volume_id__attach_post: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path: {
                volume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachVolumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_VolumeResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_volume_volumes__volume_id__detach_post: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path: {
                volume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_VolumeResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_snapshots_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                cloud?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_snapshot_snapshots_post: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_SnapshotResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_snapshots__snapshot_id__get: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_SnapshotResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_snapshot_snapshots__snapshot_id__delete: {
        parameters: {
            query?: {
                cloud?: string | null;
            };
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_images_images_get: {
        parameters: {
            query?: {
                cloud?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_ImageResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flavors_flavors_get: {
        parameters: {
            query?: {
                cloud?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_FlavorResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clouds_status_clouds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    hello_world__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    cloud_health_check_health_cloud__cloud_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cloud_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
